[chezmoidata.userlocal]
gituser = ""
mise.minimum_release_age = "0"
mise.tools = {}
mise.shell_alias = {}
ssh.authorized_keys = []

[chezmoidata.hostlocal]
compaudit.allow = []
brew.user = ""
brew.brews = []
brew.casks = []
